language: ruby
sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      before_install:
        - cd ca
        - docker build -t niacainfosys/ca-binary-base:1.6.1 -f binary-base.Dockerfile .
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push niacainfosys/ca-binary-base:1.6.1
