language: ruby
sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      before_install:
        - cd ca/workbench
        - docker build -t niacainfosys/ca-workbench-base:nightly -f ca-workbench-base.Dockerfile .
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push niacainfosys/ca-workbench-base:nightly
    - stage: build
      before_install:
        - cd ca/model-trainer
        - docker build -t niacainfosys/ca-model-trainer-base:nightly -f ca-model-trainer-base.Dockerfile .
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push niacainfosys/ca-model-trainer-base:nightly