language: ruby
sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      before_install:
        - cd experiments
        - docker build -t niacainfosys/experiments-rhel7-ubi -f rhel7-ubi.Dockerfile .
      script:
        - docker run niacainfosys/experiments-rhel7-ubi /bin/bash -c "yum list installed"
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push niacainfosys/experiments-rhel7-ubi