language: ruby
sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      before_install:
        - cd vision/multi-conda
        - docker build -t niacainfosys/multi-conda:1.0 -f multi-conda.Dockerfile .
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push niacainfosys/multi-conda:1.0