sudo: required

services:
  - docker

before_install:
  - cd vision/api
  - docker build -t niacainfosys/vision-api-gpu-base:1.2.0 -f vision-api-gpu-base.Dockerfile .
  - docker build -t niacainfosys/vision-api-base:1.2.0 -f vision-api-base.Dockerfile .
  - cd vision/workbench
  - docker build -t niacainfosys/vision-workbench-base:1.2.0 -f vision-workbench-base.Dockerfile .
  - cd vision/workflows
  - docker build -t niacainfosys/vision-workflows-base:1.2.0 -f vision-workflows-base.Dockerfile .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run niacainfosys/vision-api-gpu-base:1.2.0 /bin/bash -c "python --version; pip list; java -version; apt list --installed"
  - docker push niacainfosys/vision-api-gpu-base:1.2.0
  - docker run niacainfosys/vision-api-base:1.2.0 /bin/bash -c "python --version; pip list; java -version; apt list --installed"
  - docker push niacainfosys/vision-api-base:1.2.0
  - docker run niacainfosys/vision-workbench-base:1.2.0 /bin/bash -c "python --version; pip list; apt list --installed"
  - docker push niacainfosys/vision-workbench-base:1.2.0
  - docker run niacainfosys/vision-workflows-base:1.2.0 /bin/bash -c "python --version; pip list; apt list --installed"
  - docker push niacainfosys/vision-workflows-base:1.2.0