language: ruby
sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      before_install:
        - cd vision/api
        - docker build -t niacainfosys/vision-api-base:launchpad -f vision-api-base.Dockerfile .
      script:
        - docker run niacainfosys/vision-api-base:launchpad /bin/bash -c "python --version; pip list; java -version; apt list --installed"
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push niacainfosys/vision-api-base:launchpad
    - stage: build
      before_install:
        - cd vision/api
        - docker build -t niacainfosys/vision-api-gpu-base:launchpad -f vision-api-gpu-base.Dockerfile .
      script:
        - docker run niacainfosys/vision-api-gpu-base:launchpad /bin/bash -c "python --version; pip list; java -version; apt list --installed"
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push niacainfosys/vision-api-gpu-base:launchpad
