language: ruby
sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      before_install:
        - cd vision/api
        - docker build -t niacainfosys/vision-api-base:1.4.0 -f vision-api-base.Dockerfile .
    - stage: build
      before_install:
        - cd vision/api
        - docker build -t niacainfosys/vision-api-gpu-base:1.4.0 -f vision-api-gpu-base.Dockerfile .
    - stage: build
      before_install:
        - cd vision/tfserving
        - docker build -t niacainfosys/vision-tfserving-base:1.4.0 -f vision-tfserving-base.Dockerfile .