language: ruby
sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      before_install:
        - cd webapp-efs
        - docker build -t niacainfosys/webapp-efs-base:1.0  -f webapp-efs.Dockerfile .
      script:
        - docker run niacainfosys/webapp-efs-base:1.0 /bin/bash -c "python --version; pip list; java -version; apt list --installed"
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push niacainfosys/webapp-efs-base:1.0
