language: ruby
sudo: required

services:
  - docker

jobs:
  include:        
    - stage: build
      before_install:
        - cd ca/search
        - docker build -t niacainfosys/ca-search-base:1.6.1 -f ca-search-base.Dockerfile .
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push niacainfosys/ca-search-base:1.6.1
