sudo: required

services:
  - docker

before_install:
  - cd vision/tfserving_mkl
  - docker build -t niacainfosys/tfserving-mkl:1.2.0 -f tfserving-mkl.Dockerfile .

script:
  - docker run niacainfosys/tfserving-mkl:1.2.0 /bin/bash -c "apt list --installed"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push niacainfosys/tfserving-mkl:1.2.0